// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POCA.Banco.Model;

#nullable disable

namespace POCA.Banco.Migrations
{
    [DbContext(typeof(DbPocaContext))]
    [Migration("20250505142925_Materias")]
    partial class Materias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("POCA.Banco.Model.TbAluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aluno");

                    b.Property<string>("ContatoAluno")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("contato_aluno");

                    b.Property<int>("IdadeAluno")
                        .HasColumnType("int")
                        .HasColumnName("idade_aluno");

                    b.Property<string>("LoginAluno")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("login_aluno");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome_aluno");

                    b.Property<int>("ProgressoAluno")
                        .HasColumnType("int")
                        .HasColumnName("progresso_aluno");

                    b.Property<string>("SenhaAluno")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("senha_aluno");

                    b.HasKey("IdAluno")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NomeAluno" }, "nome_aluno_UNIQUE")
                        .IsUnique();

                    b.ToTable("tb_alunos", (string)null);
                });

            modelBuilder.Entity("POCA.Banco.Model.TbMateria", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<int?>("IdAlunoMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_aluno_materia");

                    b.Property<int?>("IdProfessorMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_professor_materia");

                    b.HasKey("IdMateria")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAlunoMateria" }, "id_aluno_materia_idx");

                    b.HasIndex(new[] { "IdProfessorMateria" }, "id_professor_materia_idx");

                    b.ToTable("tb_materias", (string)null);
                });

            modelBuilder.Entity("POCA.Banco.Model.TbProfessore", b =>
                {
                    b.Property<int>("IdProfessor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_professor");

                    b.Property<string>("ContatoProfessor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("contato_professor");

                    b.Property<string>("LoginProfessor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("login_professor");

                    b.Property<string>("MateriaProfessor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("materia_professor");

                    b.Property<string>("NomeProfessor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome_professor");

                    b.Property<string>("SenhaProfessor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("senha_professor");

                    b.HasKey("IdProfessor")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContatoProfessor" }, "contato_professor_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "LoginProfessor" }, "login_professor_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "NomeProfessor" }, "nome_professor_UNIQUE")
                        .IsUnique();

                    b.ToTable("tb_professores", (string)null);
                });

            modelBuilder.Entity("POCA.Banco.Model.TbQuesto", b =>
                {
                    b.Property<int>("IdQuestao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_questao");

                    b.Property<string>("DificuldadeQuestao")
                        .IsRequired()
                        .HasColumnType("enum('Fácil','Médio','Difícil')")
                        .HasColumnName("dificuldade_questao");

                    b.Property<string>("EnunciadoQuestao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("enunciado_questao");

                    b.Property<string>("RespostacertaQuestao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respostacerta_questao");

                    b.Property<string>("Respostaerrada1Questao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respostaerrada1_questao");

                    b.Property<string>("Respostaerrada2Questao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respostaerrada2_questao");

                    b.Property<string>("Respostaerrada3Questao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respostaerrada3_questao");

                    b.Property<string>("TemaQuestao")
                        .IsRequired()
                        .HasColumnType("enum('Teoria','Programação')")
                        .HasColumnName("tema_questao");

                    b.HasKey("IdQuestao")
                        .HasName("PRIMARY");

                    b.ToTable("tb_questoes", (string)null);
                });

            modelBuilder.Entity("POCA.Banco.Model.TbMateria", b =>
                {
                    b.HasOne("POCA.Banco.Model.TbAluno", "IdAlunoMateriaNavigation")
                        .WithMany("TbMateria")
                        .HasForeignKey("IdAlunoMateria")
                        .HasConstraintName("id_aluno_materia");

                    b.HasOne("POCA.Banco.Model.TbProfessore", "IdProfessorMateriaNavigation")
                        .WithMany("TbMateria")
                        .HasForeignKey("IdProfessorMateria")
                        .HasConstraintName("id_professor_materia");

                    b.Navigation("IdAlunoMateriaNavigation");

                    b.Navigation("IdProfessorMateriaNavigation");
                });

            modelBuilder.Entity("POCA.Banco.Model.TbAluno", b =>
                {
                    b.Navigation("TbMateria");
                });

            modelBuilder.Entity("POCA.Banco.Model.TbProfessore", b =>
                {
                    b.Navigation("TbMateria");
                });
#pragma warning restore 612, 618
        }
    }
}
