// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POCA.Banco.Model;

#nullable disable

namespace POCA.Banco.Migrations
{
    [DbContext(typeof(DbPocaContext))]
    [Migration("20250427164923_Tb_aluno")]
    partial class Tb_aluno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("POCA.Banco.Model.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory", (string)null);
                });

            modelBuilder.Entity("POCA.Banco.Model.TbAluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aluno");

                    b.Property<string>("ContatoAluno")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("contato_aluno");

                    b.Property<int>("IdadeAluno")
                        .HasColumnType("int")
                        .HasColumnName("idade_aluno");

                    b.Property<string>("LoginAluno")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("login_aluno");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome_aluno");

                    b.Property<int>("ProgressoAluno")
                        .HasColumnType("int")
                        .HasColumnName("progresso_aluno");

                    b.Property<string>("SenhaAluno")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("senha_aluno");

                    b.HasKey("IdAluno")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NomeAluno" }, "nome_aluno_UNIQUE")
                        .IsUnique();

                    b.ToTable("tb_alunos", (string)null);
                });

            modelBuilder.Entity("POCA.Banco.Model.TbQuestoes", b =>
                {
                    b.Property<int>("IdQuestao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_questao");

                    b.Property<string>("DificuldadeQuestao")
                        .IsRequired()
                        .HasColumnType("enum('Fácil','Médio','Difícil')")
                        .HasColumnName("dificuldade_questao");

                    b.Property<string>("EnunciadoQuestao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("enunciado_questao");

                    b.Property<string>("RespostacertaQuestao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respostacerta_questao");

                    b.Property<string>("Respostaerrada1Questao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respostaerrada1_questao");

                    b.Property<string>("Respostaerrada2Questao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respostaerrada2_questao");

                    b.Property<string>("Respostaerrada3Questao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respostaerrada3_questao");

                    b.Property<string>("TemaQuestao")
                        .IsRequired()
                        .HasColumnType("enum('Teoria','Programação')")
                        .HasColumnName("tema_questao");

                    b.HasKey("IdQuestao")
                        .HasName("PRIMARY");

                    b.ToTable("tb_questoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
